version: '3'

services:
  db:
    image: postgres
    restart: always
    tty: true 
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: supersecret
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  my_dbdata:
